### ISSUE TITLE
Is there logic for the full game such as declaring riichi and calculating furiten?

### ISSUE THREAD

**Issue by fumin** [dnovikoff/tempai-core#2]
Thanks for this great library.
I wonder is there an example, possibly built on top of this library, that contains a playable game in the terminal?
I imagine such a full implementation of the game in the terminal might require additional logic to handle proposing melds, riichi, and imposing furiten.

**Comment by dnovikoff** [comment]
Hello! Thanks for the interest to my library. As it is mentioned in the https://github.com/dnovikoff/tempai-core/blob/master/README.md, this package is the extraction of core code from my private repo. This library does not contain the game mechanics. And at the moment there are no plans to reveal other layers of my code.
Still you can find a playable simplified example of a game for two players here https://github.com/dnovikoff/tenhou/tree/master/cmd/pimboo-server
See the README file here https://github.com/dnovikoff/tenhou/blob/master/README.md

Feel free to ask other questions on library functionality.

**Comment by fumin** [comment]
Hi Dnovikoff

Thanks for this information, and for pointing to pimboo-server. 
I have had cursory look at pimboo-server, and if I understand correctly, it outsources the game mechanics to tenhou.net, doesn't it?

I am aware that this might be too much to ask, but I wonder if it is possible for you to share some parts of your private repo regarding the game mechanics, under certain terms that you dictate?
Happy to talk about this offline, too.

**Comment by dnovikoff** [comment]
> I have had cursory look at pimboo-server, and if I understand correctly, it outsources the game mechanics to tenhou.net, doesn't it?

The game logic is still inside a server. The purpose of that example is to show the work of tenhou protocol implementation.

> I am aware that this might be too much to ask, but I wonder if it is possible for you to share some parts of your private repo regarding the game mechanics, under certain terms that you dictate?

Not sure I want to share other layers. Could you please describe your purposes of library usage? I think you can contact me via some messanger. Do you use Telegram? I also have Skype, but I dont use it much.

**Comment by fumin** [comment]
> The game logic is still inside a server. The purpose of that example is to show the work of tenhou protocol implementation.
Thanks for the clarification.

> Not sure I want to share other layers. Could you please describe your purposes of library usage? I think you can contact me via some messanger. Do you use Telegram? I also have Skype, but I dont use it much.
My intended use of the library is to use it as a simulator to generate training data. Ultimately, I am planning to use this generated data to train a bot. I do use Telegram, and my handle is @ylfawaw on Telegram. Happy to discuss more about my use case privately.

**Comment by dnovikoff** [comment]
@fumin please check https://github.com/dnovikoff/mahjong-api
